projects:
  stackstorefrontend:
    schemaPath: amplify/backend/api/stackstorefrontend/build/schema.graphql
    includes:
      - src/graphql/
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: sa-east-1
        apiId: null
        maxDepth: 2
